### ISSUE TITLE
Deploy

### ISSUE THREAD

**Issue by SapkotaRajat** [44hukum/creators#2]
@44hukum

**Comment by 44hukum** [comment]
> @44hukum

@SapkotaRajat, Code deployment is automatic for every change pushed into the master or main branch. FYI: Do not make repo private, that will create a deployment issue. @dheerazsah

**Comment by SapkotaRajat** [comment]
@44hukum I have been working on this main branch and there is no changes in deployment what am I missing?
Am I supossed to do anything for changes to be dislpayed?
